name: 5-minute-cron
on:
  schedule:
    - cron: "*/5 * * * *"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request POST \
          --url 'https://node-vera.vercel.app/api/notify' \
          --header 'Content-Type: application/json' \
          --data '{"secret":${{ secrets.SECRET_KEY }}}'
